version: '2'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --init-file=/tmp/init.sql
    volumes:
      - ./init.sql:/tmp/init.sql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: developer

  redis:
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

  gunicorn:
    restart: always
    build: ./
    expose:
      - "8081"
    volumes:
      - /home/app
    command: /usr/bin/supervisord -c supervisord.conf
    depends_on:
      - mysql
      - redis
    ports:
      - "8081:8081"